### ISSUE TITLE
--status looks incomplete

### ISSUE THREAD

**Issue by ohmantics** [mikenemat/plum-probe#2]
It almost looks like the file was truncated when you committed it.

**Comment by philippelaurent** [comment]
If you place `print (ret)` at the end of the file, you'll get the JSON string showing the metrics returned. You can massage the data any way you want after that.

Example output:
{u'lightpad_metrics': [{u'lpid': u'blahblahblahblahblahblah', u'power': 8, u'level': 180}], u'power': 8, u'level': 180}

**Comment by mikenemat** [comment]
This is fixed. Apologies for how long it took to clean this up.

If you guys want the JSON data parsed out, just let me know

**Comment by philippelaurent** [comment]
Thanks! Currently adopting your efforts for the Indigo Domotics platform, and will release the plugin when done. Interested in any feedback you have for the proximity sensing side of the switch. Read about your comments on the OpenHAB site.

**Comment by mikenemat** [comment]
The motion sensing is really, really cool. There is a numerical value that comes along with the motion events which I haven't quite been able to decipher yet. I think it has something to do with the strength of the motion detection. That's really important, because I tend to get approximately 1 "phantom" motion event an hour right now. It's probably pretty easy to aggregate the logs over a couple of hours while playing around with the motion sensor to track it down. If you look in the openHab plugin, my binding will log a "pirSensor" event whenever it receives one from a lightpad, along with the numerical value it receives.

My other thought at this point is to just break open one of my spare Plum light pads and root it using hardware tools to gain access to all of this information. We'll see if I get bored enough to do that :)
